name: Test Core Modules
on:
  pull_request:
    types:
      - "labeled"
  workflow_dispatch:
env:
  TF_VAR_project: "NS8-CI"
  TF_VAR_domain: "ci.nethserver.net"
  NS8_LEADER_NODES: "dn1 cs1"
  NS8_CORE_MODULES: "core traefik loki promtail ldapproxy"

jobs:
  ns8:
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event.label.name == 'testing'
    name: Find NS8 cluster informations
    runs-on: ubuntu-latest
    outputs:
      nodes: ${{ steps.nodes.outputs.list }}
      modules: ${{ steps.modules.outputs.list }}
      tag: ${{ steps.tag.outputs.name }}
      short_sha: ${{ steps.short_sha.outputs.value }}
    steps:
      - id: nodes
        run: |
          nodes=$(jq -ncR '[inputs]' <<< "$(echo $NS8_LEADER_NODES | tr ' ' '\n')")
          echo "::set-output name=list::${nodes}"
      - id: tag
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]
          then
            tag=${{ github.head_ref }}
          else
            tag="${{ github.ref_name }}"
          fi
          if [ "$tag" = "main" ]
          then
            tag="latest"
          fi
          echo "::set-output name=name::${tag}"
      - id: short_sha
        run: echo "::set-output name=value::$( echo ${{ github.sha }} | cut -c1-8 )"
      - id: modules
        run: |
          modules_list='[]'
          for module in ${NS8_CORE_MODULES}
          do
            res=$(podman search --limit 150 --list-tags   --format json   ghcr.io/nethserver/${module} | jq 'any(.[].Tags[]; . == "${{ steps.tag.outputs.name }}")')
            if [ "$res" = "true" ]
            then
              modules_list=$(echo "${modules_list}"  | jq -c --arg m ghcr.io/nethserver/${module}:${{ steps.tag.outputs.name }} ' . + [$m]')
            fi
          done
          echo "::set-output name=list::${modules_list}"
  gh_runner:
    needs: ns8
    uses: Amygos/ns8-github-actions/.github/workflows/test-on-ubuntu-runner.yml@main
    with:
      path: core/
      setup_cluster: false
      coremodules: ${{ join(fromJSON(needs.ns8.outputs.modules), ' ' ) }}
      debug_shell: true
  remove_label:
    name: "Cleaup PR label"
    runs-on: ubuntu-latest
    needs:
      - gh_runner
    if: |
      github.event.label.name == 'testing' &&
      needs.infra_destroy.result == 'success' &&
      always()
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: testing
